# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: BlogBox

# Below the site title
tagline: Tales of a digital nomad.

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  BlogBox is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net.

# The base hostname & protocol of your site for where absolute urls are needed
url: https://blogbox.netlify.app

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: 홈
  url: /
#- text: 포트폴리오
#  url: /portfolio/
- text: 블로그
  url: /blog/
- text: 소개
  url: /about/

# Author information - author info at the bottom of the post
author_name: "변석진"
author_bio: "유니티 클라이언트 지망하는 변석진입니다."
author_location: "경기, 남양주"
author_image: authorimage.jpg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://justgoodthemes.com/

# Social links in the site footer
github_username: "bsj2234"
youtube_username: "@siko102"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# If you're using GitHub Pages, add:
safe: false

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax

# Portfolio
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

mermaid: true